name: hello_world
on: [push, workflow_dispatch]
jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Print Hello World
        run: echo "Hello World"

      - name: Print message
        run: echo "This is my first YAML program"
